name: 🪲Debugging Workflow


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:


jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: ReInstall DotNet Tool
      run: ../../InstallTool.ps1

    - name: Restore DotNet Tools
      run: dotnet tool restore

    - name: Run Debugging Workflow
      run: dotnet cicd DebugTask
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Build Status Check
      run: dotnet cicd PRBuildStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
